### ISSUE TITLE
Property Attribute

### ISSUE THREAD

**Issue by K4L4Uz** [lhzcm/LHZ.FastJson#2]
add JsonPropertyAttribute to change the names of properties

**Comment by lhzcm** [comment]
It has been added to the development plan, so stay tuned, and thank you for your suggestions

**Comment by lhzcm** [comment]
## The JsonPropertyAttribute function has been developed
You can change the name of a property by adding "LHZ.FastJson.Json.Attributes.JsonPropertyAttribute" to a class's properties. The usage method is shown in the picture.
<img width="345" alt="Snipaste_2024-09-27_19-41-35" src="https://github.com/user-attachments/assets/62ac00c6-2cd4-4824-bb59-b49a15294261">
